### ISSUE TITLE
When will the codes be released?

### ISSUE THREAD

**Issue by sheMnapion** [Sangminhong/ACL-SPC_PyTorch#1]
Looking forward to trying your self-supervised framework!

**Comment by ark1234** [comment]
Me too!

**Comment by myavartanoo** [comment]
Thank you very much for your interest in our paper. 
We will release the code very soon.

**Comment by sheMnapion** [comment]
Thanks for the reply! Wondering are current codes final version? And could you please check the link for the pretrained model, as it is not working?

**Comment by Sangminhong** [comment]
> Thanks for the reply! Wondering are current codes final version? And could you please check the link for the pretrained model, as it is not working?

Thank you for your interest! The current codes are the final version and I have updated the link for the pretrained model.
