### ISSUE TITLE
would you please share test.txt and train.txt for loading shapeNet H5 files, thank you.

### ISSUE THREAD

**Issue by MillyMaMa** [Sangminhong/ACL-SPC_PyTorch#11]
Would you please share test.txt and train.txt for loading shapeNet H5 files, thank you very much.

        if split=="test":
           metadata = open(self.root+'/splits/'+self.cls_name+'_test.txt','r').readlines()
           self.metadata = [x.split('\n')[0] for x in metadata]
           self.partial = h5py.File(self.root+ self.cls_name+ '_data.h5','r')
           self.gt = h5py.File(self.root+ self.cls_name+ '_gt.h5','r')
           
        elif split=="train":
           metadata = open(self.root+'/splits/'+self.cls_name+'_train.txt','r').readlines()
           self.metadata = [x.split('\n')[0] for x in metadata]  
           self.partial = h5py.File(self.root+ self.cls_name+ '_data.h5','r')  
           self.gt = h5py.File(self.root+ self.cls_name+ '_gt.h5','r')

**Comment by Sangminhong** [comment]
Hi, give me an email to sangminhong1227@gmail.com and I then will send those files.

**Comment by MillyMaMa** [comment]
I have send email to you, pleae check it, thank you.

**Comment by MillyMaMa** [comment]
> Hi, give me an email to [sangminhong1227@gmail.com](mailto:sangminhong1227@gmail.com) and I then will send those files.

I have send email to you, pleae check it, thank you. @Sangminhong

**Comment by Sangminhong** [comment]
> > Hi, give me an email to [sangminhong1227@gmail.com](mailto:sangminhong1227@gmail.com) and I then will send those files.
> 
> I have send email to you, pleae check it, thank you. @Sangminhong

Hi, I didn't get any email. Could you resend it?

**Comment by junkangma** [comment]
211339050@qq.com,Thanks!

**Comment by Aron-max1** [comment]
Hi, if you haven't received my email too, can you send it to the email address below：[211339050@qq.com](mailto:211339050@qq.com)
