### ISSUE TITLE
Would you please share the SemanticKITTI dataset used in ACL-SPC ?

### ISSUE THREAD

**Issue by MillyMaMa** [Sangminhong/ACL-SPC_PyTorch#12]
Dear author @Sangminhong ：
I plan to train ACL-SPC on SemanticKITTI dataset，I download it from SemanticKITTI website following the guidance in [issue 2](https://github.com/Sangminhong/ACL-SPC_PyTorch/issues/2),
but I find its formate is not .pkl while the code need .pkl to load SemanticKITTI .

```
class SemanKITTIDataset:
    def _load_dataset(self, split):
        self.data = []
        for sequence_id in self.split_map[split]:
            fname = osp.join(self.directory, '{:02d}.pkl'.format(sequence_id))
            with open(fname, 'rb') as f:
                instances = pickle.load(f)
```

Would you please share the SemanticKITTI dataset used in ACL-SPC  with me?
I have send emails to you for two times,  please check them, appreciate for your time.

**Comment by ZhiXia-SEU** [comment]
Have you solved it yet？
