### ISSUE TITLE
The download path of the datasets

### ISSUE THREAD

**Issue by IvanXie416** [Sangminhong/ACL-SPC_PyTorch#2]
Thanks for your outstanding work.
Could you please provide the download path of the datasets?
Thank you!

**Comment by Sangminhong** [comment]
> Thanks for your outstanding work. Could you please provide the download path of the datasets? Thank you!

Sorry for the late reply.
1. ShapeNet: I followed the process in https://github.com/eldar/differentiable-point-clouds.
2. SemanticKITTI :  http://semantic-kitti.org/dataset.html. 
3. MatterPort3D, ScanNet, KITTI : I followed the process in https://github.com/xuelin-chen/pcl2pcl-gan-pub. 

Thank you.
