### ISSUE TITLE
Real-world datasets

### ISSUE THREAD

**Issue by Aron-max1** [Sangminhong/ACL-SPC_PyTorch#7]
Thank you for your work!
I want to konw the experiments in real-world datasets,why you train on test_datasets,and not tested on other datasets.

**Comment by Aron-max1** [comment]
@Sangminhong  I modified it to train on the train_dataset and test on the test_dataset, but it seems that I did not get the results in the paper.

**Comment by D2Simon** [comment]
The same as me, the result is like a noise
